# Generated by Django 5.1.7 on 2025-04-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ai', 'Artificial Intelligence'), ('web', 'Web Development'), ('coding', 'Coding'), ('tech', 'Technology'), ('featured', 'Featured'), ('foryou', 'For you')], default='foryou', max_length=100),
        ),
    ]
